# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J6dKH0hB_RAYGLIMr_UR0tQZ5Zs3mam2
"""

from google.colab import files
uploaded = files.upload()

from google.colab import files
uploaded = files.upload()

pip install chronos-forecasting

import pandas as pd  # requires: pip install 'pandas[pyarrow]'
from chronos import Chronos2Pipeline

pipeline = Chronos2Pipeline.from_pretrained("amazon/chronos-2", device_map="cpu")

# Load historical target values and past values of covariates
context_df = pd.read_csv("672.csv")

# (Optional) Load future values of covariates
test_df = pd.read_csv("24.csv")
future_df = test_df.drop(columns="target")

# Generate predictions with covariates
pred_df = pipeline.predict_df(
    context_df,
    future_df=future_df,
    prediction_length=24,  # Number of steps to forecast
    quantile_levels=[0.1, 0.5, 0.9],  # Quantile for probabilistic forecast
    id_column="id",  # Column identifying different time series
    timestamp_column="timestamp",  # Column with datetime information
    target="target",  # Column(s) with time series values to predict
)

import matplotlib.pyplot as plt
import pandas as pd

context_df["timestamp"] = pd.to_datetime(context_df["timestamp"])
test_df["timestamp"]    = pd.to_datetime(test_df["timestamp"])
pred_df["timestamp"]    = pd.to_datetime(pred_df["timestamp"])

series_id = context_df["id"].iloc[0]

ctx_one  = context_df[context_df["id"] == series_id].copy()
test_one = test_df[test_df["id"] == series_id].copy()
pred_one = pred_df[pred_df["id"] == series_id].copy()

ts_context = (
    ctx_one.set_index("timestamp")["target"].tail(256)
)

ts_ground_truth = (
    test_one.set_index("timestamp")["target"]
)

ts_pred = (
    pred_one.set_index("timestamp")
)

start_plot = ts_context.index.min()
end_plot   = ts_pred.index.max()

plt.figure(figsize=(12, 3))

ts_context[start_plot:end_plot].plot(
    label="historical data", color="xkcd:azure"
)
ts_ground_truth[start_plot:end_plot].plot(
    label="future data (ground truth)", color="xkcd:grass green"
)
ts_pred["predictions"].plot(
    label="forecast", color="xkcd:violet"
)

plt.fill_between(
    ts_pred.index,
    ts_pred["0.1"],
    ts_pred["0.9"],
    alpha=0.5,
    label="prediction interval",
    color="xkcd:light lavender",
)

plt.legend()
plt.xlabel("timestamp")
plt.ylabel("target")
plt.tight_layout()
plt.show()