# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YI_D2TviUF_mkPLRuFZ9aLXHCiURKUVn
"""

from google.colab import files
uploaded = files.upload()

import numpy as np
data = np.load('train_dataset.npy',allow_pickle=True)

print(type(data))
print(data.shape)
print(data.dtype)

obj = data.item()
print(type(obj))

print(obj.keys())

X = obj['feature']
y = obj['label']

print("feature type:", type(X), "shape:", X.shape)
print("lable type:", type(y), "shape:", y.shape)

N = X.shape[0]
print("Number of training samples:", N)

unique, counts = np.unique(y, return_counts=True)
for label, cnt in zip(unique, counts):
    print(f"Class {int(label)} samples:", cnt)

M = X.shape[1]
print("Number of sensor measurements (features):", M)

import numpy as np

# 按照你给出的 mpc.branch 数据（只写前两列 fbus, tbus 即可）
branch = np.array([
    [1,  2],
    [1,  5],
    [2,  3],
    [2,  4],
    [2,  5],
    [3,  4],
    [4,  5],
    [4,  7],
    [4,  9],
    [5,  6],
    [6, 11],
    [6, 12],
    [6, 13],
    [7,  8],
    [7,  9],
    [9, 10],
    [9, 14],
    [10,11],
    [12,13],
    [13,14],
], dtype=int)

n_branches = branch.shape[0]   # 支路数 = 20
n_buses = 14                   # IEEE 14-bus 系统

# 初始化 A 为全 0
A = np.zeros((n_branches, n_buses), dtype=int)

# 构造关联矩阵
for l in range(n_branches):
    fbus = branch[l, 0]  # 起点母线
    tbus = branch[l, 1]  # 终点母线

    # Python 索引从 0 开始，母线从 1 开始 → 要减 1
    A[l, fbus - 1] =  1
    A[l, tbus - 1] = -1

# 输出结果
print("Incidence matrix A shape:", A.shape)  # (20, 14)
print(A)

import numpy as np

# -----------------------------
# 1. 输入 mpc.branch 数据
#    列顺序与 MATPOWER 一致:
#    fbus, tbus, r, x, b, rateA, rateB, rateC, ratio, angle, status, angmin, angmax
# -----------------------------
branch = np.array([
    [1,  2, 0.01938, 0.05917, 0.0528, 0, 0, 0, 0,     0, 1, -360, 360],
    [1,  5, 0.05403, 0.22304, 0.0492, 0, 0, 0, 0,     0, 1, -360, 360],
    [2,  3, 0.04699, 0.19797, 0.0438, 0, 0, 0, 0,     0, 1, -360, 360],
    [2,  4, 0.05811, 0.17632, 0.0340, 0, 0, 0, 0,     0, 1, -360, 360],
    [2,  5, 0.05695, 0.17388, 0.0346, 0, 0, 0, 0,     0, 1, -360, 360],
    [3,  4, 0.06701, 0.17103, 0.0128, 0, 0, 0, 0,     0, 1, -360, 360],
    [4,  5, 0.01335, 0.04211, 0.0000, 0, 0, 0, 0,     0, 1, -360, 360],
    [4,  7, 0.00000, 0.20912, 0.0000, 0, 0, 0, 0.978, 0, 1, -360, 360],
    [4,  9, 0.00000, 0.55618, 0.0000, 0, 0, 0, 0.969, 0, 1, -360, 360],
    [5,  6, 0.00000, 0.25202, 0.0000, 0, 0, 0, 0.932, 0, 1, -360, 360],
    [6, 11, 0.09498, 0.19890, 0.0000, 0, 0, 0, 0,     0, 1, -360, 360],
    [6, 12, 0.12291, 0.25581, 0.0000, 0, 0, 0, 0,     0, 1, -360, 360],
    [6, 13, 0.06615, 0.13027, 0.0000, 0, 0, 0, 0,     0, 1, -360, 360],
    [7,  8, 0.00000, 0.17615, 0.0000, 0, 0, 0, 0,     0, 1, -360, 360],
    [7,  9, 0.00000, 0.11001, 0.0000, 0, 0, 0, 0,     0, 1, -360, 360],
    [9, 10, 0.03181, 0.08450, 0.0000, 0, 0, 0, 0,     0, 1, -360, 360],
    [9, 14, 0.12711, 0.27038, 0.0000, 0, 0, 0, 0,     0, 1, -360, 360],
    [10,11, 0.08205, 0.19207, 0.0000, 0, 0, 0, 0,     0, 1, -360, 360],
    [12,13, 0.22092, 0.19988, 0.0000, 0, 0, 0, 0,     0, 1, -360, 360],
    [13,14, 0.17093, 0.34802, 0.0000, 0, 0, 0, 0,     0, 1, -360, 360],
], dtype=float)

# -----------------------------
# 2. 基本尺寸信息
# -----------------------------
n_branches = branch.shape[0]   # 支路数 = 20
n_buses = 14                   # IEEE 14-bus

# -----------------------------
# 3. 提取 fbus, tbus, x
# -----------------------------
fbus = branch[:, 0].astype(int)
tbus = branch[:, 1].astype(int)
x = branch[:, 3]               # 第 4 列是电抗 x

# -----------------------------
# 4. 计算线路电纳 b = 1/x
#    对 x = 0 的支路（如果有）设 b = 0（或你自己决定怎么处理）
# -----------------------------
b = np.zeros(n_branches)
nonzero_x = (x != 0)
b[nonzero_x] = 1.0 / x[nonzero_x]

print("Line reactances x:\n", x)
print("Line susceptances b = 1/x (x=0 -> b=0):\n", b)

# -----------------------------
# 5. 构造关联矩阵 A (你之前已经做过，这里再完整写一遍)
# -----------------------------
A = np.zeros((n_branches, n_buses), dtype=float)

for ell in range(n_branches):
    A[ell, fbus[ell] - 1] =  1.0  # 起点
    A[ell, tbus[ell] - 1] = -1.0  # 终点

print("Incidence matrix A shape:", A.shape)
print("A =\n", A)

# -----------------------------
# 6. 构造 B_pf = diag(b) * A
# -----------------------------
Bpf = np.diag(b) @ A
print("\nB_pf shape:", Bpf.shape)
print("B_pf =\n", Bpf)

# -----------------------------
# 7. 构造 B_pi = A^T * diag(b) * A
# -----------------------------
Bpi = A.T @ np.diag(b) @ A
print("\nB_pi shape:", Bpi.shape)
print("B_pi =\n", Bpi)

# -----------------------------
# 8. 一些结构上的检查（可选但推荐）
# -----------------------------
# 8.1 对称性检查
print("\nIs B_pi symmetric? ->", np.allclose(Bpi, Bpi.T))

# 8.2 行和是否接近 0（数值误差允许）
row_sums = Bpi.sum(axis=1)
print("Row sums of B_pi (should be close to 0):\n", row_sums)

H_full = np.vstack([Bpf, Bpi])  # shape: (34, 14)

# 2. 去掉参考母线（bus 1）这一列，得到 34 x 13 的 H
#    假设 bus 1 是参考母线，对应第 0 列
H = H_full[:, 1:]  # 只保留列 1~13 (对应 bus 2~14)

print("H shape:", H.shape)  # (34, 13)

# 测量数量
n_pf = 20   # branch power flow measurements
n_pi = 14   # bus power injection measurements
n_meas = n_pf + n_pi  # 34

# 噪声标准差
sigma_pf = 0.02
sigma_pi = 0.01

# 构造方差向量
var_pf = sigma_pf**2 * np.ones(n_pf)  # 前 20 个
var_pi = sigma_pi**2 * np.ones(n_pi)  # 后 14 个
variances = np.concatenate([var_pf, var_pi])  # shape: (34,)

# 协方差矩阵 R = diag(variances)，权重矩阵 W = R^{-1}
R = np.diag(variances)          # 34 x 34
W = np.diag(1.0 / variances)    # 34 x 34

print("R shape:", R.shape)
print("W shape:", W.shape)

def wls_state_estimation(z, H, W):
    """
    z: 测量向量 (34,)
    H: 测量矩阵 (34, 13)
    W: 权重矩阵 R^{-1} (34, 34)
    返回: x_hat (13,)
    """
    # 确保 z 是列向量形式 (34, 1)
    z = np.asarray(z).reshape(-1, 1)  # (34, 1)

    # 计算 (H^T W H)
    HTWH = H.T @ W @ H  # 13 x 13
    # 计算右端项 (H^T W z)
    HTWz = H.T @ W @ z  # 13 x 1

    # 求解 (H^T W H) x = H^T W z
    # 用 np.linalg.solve 比直接求逆更稳定
    x_hat = np.linalg.solve(HTWH, HTWz)  # 13 x 1

    return x_hat.flatten()  # 返回为 1D 向量 (13,)# 假设已经有 train_X, train_y
# train_X.shape = (N, 34)
# train_y.shape = (N,)

# 分别存放每一类样本的估计结果
x_hat_class0 = []
x_hat_class1 = []
x_hat_class2 = []

for z, label in zip(X,y):
    x_hat = wls_state_estimation(z, H, W)  # (13,)
    if label == 0:
        x_hat_class0.append(x_hat)
    elif label == 1:
        x_hat_class1.append(x_hat)
    elif label == 2:
        x_hat_class2.append(x_hat)

x_hat_class0 = np.array(x_hat_class0)  # shape: (N0, 13)
x_hat_class1 = np.array(x_hat_class1)  # shape: (N1, 13)
x_hat_class2 = np.array(x_hat_class2)  # shape: (N2, 13)

print("Class 0 estimated states shape:", x_hat_class0.shape)
print("Class 1 estimated states shape:", x_hat_class1.shape)
print("Class 2 estimated states shape:", x_hat_class2.shape)

x_hat_class0[0]

x_hat_class1[0]

N = X.shape[0]

X_hat = np.zeros((N, H.shape[1]))  # 保存所有样本的状态估计 (N, 13)
R_all = np.zeros((N, X.shape[1]))  # 保存所有样本的残差向量 (N, 34)

for i in range(N):
    z_i = X[i]                      # 第 i 个样本的测量 z (34,)
    x_hat_i = wls_state_estimation(z_i, H, W)   # (13,)
    z_hat_i = H @ x_hat_i           # 预测测量 (34,)
    r_i = z_i - z_hat_i             # 残差向量 (34,)

    X_hat[i, :] = x_hat_i
    R_all[i, :] = r_i

# 4. 按类别分别提取残差（可选）
res_class0 = R_all[y == 0]   # 所有标签为 0 的样本的残差
res_class1 = R_all[y == 1]   # 所有标签为 1 的样本的残差
res_class2 = R_all[y == 2]   # 所有标签为 2 的样本的残差

print("R_all shape (all residuals):", R_all.shape)
print("Class 0 residuals shape:", res_class0.shape)
print("Class 1 residuals shape:", res_class1.shape)
print("Class 2 residuals shape:", res_class2.shape)

import numpy as np
from scipy.stats import chi2

# ----------------------------------------
# 1. 已有数据：
#    X      : (N, 34)  所有测量样本
#    H      : (34, 13) 测量矩阵（已去掉参考母线列）
#    W = R^{-1}: (34, 34) 权重矩阵
#    R_all  : (N, 34)  对应上面的循环算好的所有残差向量
# ----------------------------------------

# 如果你还没显式保存 R（协方差矩阵），可以由 W 反推：
# (可选，若你之前已经有 R，可直接使用之前的 R)
R = np.linalg.inv(W)  # (34, 34)

# 2. 为每个样本计算 BDD 统计量 J_i = r_i^T R^{-1} r_i = r_i^T W r_i
N = X.shape[0]
J_all = np.zeros(N)

for i in range(N):
    r_i = R_all[i, :].reshape(-1, 1)   # (34, 1)
    # 统计量 J_i = r_i^T W r_i   (也等价于 r_i^T R^{-1} r_i)
    J_all[i] = float(r_i.T @ W @ r_i)

print("J_all shape:", J_all.shape)     # (N,)

# 3. 计算卡方分布自由度：k = m - n
m = X.shape[1]      # 测量个数 m = 34
n = H.shape[1]      # 状态个数 n = 13 (bus 2~14 angles)
df = m - n          # degree of freedom = 34 - 13 = 21
print("Degree of freedom (df):", df)

# 4. 设定目标假正率 alpha = 5%，求 95% 分位点作为阈值 gamma
alpha = 0.05
p = 1 - alpha       # 0.95

gamma = chi2.ppf(p, df)
print("BDD threshold gamma:", gamma)

# 5. 基于阈值判断是否报警：J_i > gamma 则判为“有攻击/坏数据”
#    下面给出一个二元检测结果数组：1 表示检测为攻击，0 表示检测为正常
bdd_decision = (J_all > gamma).astype(int)  # (N,)

# bdd_decision[i] = 1 表示第 i 个样本被 BDD 判为“有问题”
print("Number of samples flagged as bad/attacked:", bdd_decision.sum())

# 5) 根据阈值判断是否报警：J_i > gamma -> 1 (alarm), else 0 (no alarm)
bdd_decision = (J_all > gamma).astype(int)  # (N,)

# 6) 按类别统计报警率
def alarm_rate_for_class(label):
    idx = (y == label)
    if idx.sum() == 0:
        return np.nan
    return bdd_decision[idx].mean()

alarm_normal = alarm_rate_for_class(0)
alarm_fdi    = alarm_rate_for_class(1)
alarm_random = alarm_rate_for_class(2)

print("Alarm rate (normal, class 0):", alarm_normal)
print("Alarm rate (FDI, class 1):   ", alarm_fdi)
print("Alarm rate (random, class 2):", alarm_random)

import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.svm import SVC, LinearSVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, f1_score

# -----------------------------
# 1. 选取 normal 和 FDI 样本
# -----------------------------
mask_01 = (y == 0) | (y == 1)
X_bin = X[mask_01]          # 只保留 normal 和 FDI
y_bin = y[mask_01]

# 定义：FDI 为正类 (1), normal 为负类 (0)
# 若数据中 FDI 标签是 1，normal 是 0，则不用改；否则需要重映射

# -----------------------------
# 2. 划分训练集/验证集
# -----------------------------
X_train, X_valid, y_train, y_valid = train_test_split(
    X_bin, y_bin, test_size=0.2, random_state=42, stratify=y_bin
)

# 线性 SVM
lin_svm = LinearSVC(random_state=42)

param_grid_lin = {
    "C": [0.01, 0.1, 1, 10, 100]
}

grid_lin = GridSearchCV(
    lin_svm, param_grid_lin,
    cv=5, scoring="f1", n_jobs=-1
)
grid_lin.fit(X_train, y_train)

best_lin = grid_lin.best_estimator_
y_pred_lin = best_lin.predict(X_valid)

# 计算 TPR, FPR, F1
tn, fp, fn, tp = confusion_matrix(y_valid, y_pred_lin, labels=[0,1]).ravel()
TPR_lin = tp / (tp + fn)
FPR_lin = fp / (tn + fp)
F1_lin = f1_score(y_valid, y_pred_lin, pos_label=1)

print("Linear SVM: best C =", grid_lin.best_params_["C"])
print("TPR (FDI detection):", TPR_lin)
print("FPR (false alarm on normal):", FPR_lin)
print("F1 score:", F1_lin)

rbf_svm = SVC(kernel="rbf", probability=False, random_state=42)

param_grid_rbf = {
    "C": [0.1, 1, 10, 100],
    "gamma": ["scale", 0.1, 0.01, 0.001]
}

grid_rbf = GridSearchCV(
    rbf_svm, param_grid_rbf,
    cv=5, scoring="f1", n_jobs=-1
)
grid_rbf.fit(X_train, y_train)

best_rbf = grid_rbf.best_estimator_
y_pred_rbf = best_rbf.predict(X_valid)

tn, fp, fn, tp = confusion_matrix(y_valid, y_pred_rbf, labels=[0,1]).ravel()
TPR_rbf = tp / (tp + fn)
FPR_rbf = fp / (tn + fp)
F1_rbf = f1_score(y_valid, y_pred_rbf, pos_label=1)

print("RBF SVM: best params =", grid_rbf.best_params_)
print("TPR:", TPR_rbf)
print("FPR:", FPR_rbf)
print("F1:", F1_rbf)

dt = DecisionTreeClassifier(random_state=42)

param_grid_dt = {
    "max_depth": [3, 5, 10, None],
    "min_samples_leaf": [1, 2, 5, 10]
}

grid_dt = GridSearchCV(
    dt, param_grid_dt,
    cv=5, scoring="f1", n_jobs=-1
)
grid_dt.fit(X_train, y_train)

best_dt = grid_dt.best_estimator_
y_pred_dt = best_dt.predict(X_valid)

tn, fp, fn, tp = confusion_matrix(y_valid, y_pred_dt, labels=[0,1]).ravel()
TPR_dt = tp / (tp + fn)
FPR_dt = fp / (tn + fp)
F1_dt = f1_score(y_valid, y_pred_dt, pos_label=1)

print("Decision Tree: best params =", grid_dt.best_params_)
print("TPR:", TPR_dt)
print("FPR:", FPR_dt)
print("F1:", F1_dt)

!pip install -U scikit-learn xgboost

import sklearn
import xgboost

print("scikit-learn version:", sklearn.__version__)
print("xgboost version:", xgboost.__version__)

X_test = np.load('test_feature.npy')
print(type(X_test), X_test.shape)

import numpy as np

# -----------------------------
# 1. 选取 normal (0) 和 FDI (1) 样本
# -----------------------------
mask_01 = (y == 0) | (y == 1)
X_bin = X[mask_01].copy()      # (N01, 34)
y_bin = y[mask_01].copy()      # (N01,)

# 确保标签是整数类型（很重要）
y_bin = y_bin.astype(int)

# 如果你想加入 BDD 统计量作为额外特征（推荐），可以这样做：
# 注意：J_all 应与 X 同样顺序
J_bin = J_all[mask_01].reshape(-1, 1)   # (N01, 1)
# 拼接成 [测量特征, BDD统计量] -> (N01, 35)
X_bin_aug = np.hstack([X_bin, J_bin])

# 你可以选择用 X_bin 或 X_bin_aug 作为特征：
USE_AUG = True  # 如果想只用原测量，把这里改为 False

if USE_AUG:
    X_used = X_bin_aug
else:
    X_used = X_bin

print("X_used shape:", X_used.shape)

# 这里 y_bin 已经是 int，可以安全使用 bincount
print("Class balance (normal vs FDI):", np.bincount(y_bin))

X_train, X_valid, y_train, y_valid = train_test_split(
    X_used, y_bin,
    test_size=0.2,
    random_state=42,
    stratify=y_bin  # 保持类别比例
)

print("Train size:", X_train.shape[0], "Valid size:", X_valid.shape[0])

# -----------------------------
# 3. 定义 XGBoost 模型和超参数网格
# -----------------------------
xgb = XGBClassifier(
    objective="binary:logistic",  # 二分类
    eval_metric="logloss",        # 避免警告
    use_label_encoder=False,
    random_state=42,
    n_jobs=-1
)

param_grid_xgb = {
    "n_estimators": [100, 200],
    "max_depth": [3, 4, 6],
    "learning_rate": [0.05, 0.1],
    "subsample": [0.8, 1.0],
    "colsample_bytree": [0.8, 1.0]
}

grid_xgb = GridSearchCV(
    xgb,
    param_grid_xgb,
    cv=5,
    scoring="f1",   # 以 FDI 这一正类的 F1 score 为调参目标
    n_jobs=-1,
    verbose=1
)

grid_xgb.fit(X_train, y_train)

best_xgb = grid_xgb.best_estimator_
print("Best params:", grid_xgb.best_params_)

# -----------------------------
# 4. 在验证集上评估 TPR, FPR, F1
# -----------------------------
y_pred_valid = best_xgb.predict(X_valid)

tn, fp, fn, tp = confusion_matrix(y_valid, y_pred_valid, labels=[0, 1]).ravel()

TPR = tp / (tp + fn)   # 召回率：FDI 中判成 FDI 的比例
FPR = fp / (tn + fp)   # 误报率：normal 中误判为 FDI 的比例
F1  = f1_score(y_valid, y_pred_valid, pos_label=1)

print(f"XGBoost (validation) -> TPR: {TPR:.4f}, FPR: {FPR:.4f}, F1: {F1:.4f}")

import numpy as np
from xgboost import XGBClassifier

# -----------------------------
# 5.1 加载 test_feature，并构造与训练一致的特征
# -----------------------------
# 假设 test_feature.npy 在当前目录
X_test_raw = np.load('test_feature.npy')   # (M, 34)

# 对 test_feature 里的每个样本做 WLS -> 残差 -> BDD 统计量
M = X_test_raw.shape[0]
R_test_all = np.zeros_like(X_test_raw)   # (M, 34) 残差
J_test_all = np.zeros(M)                 # (M,)   BDD 统计量

for i in range(M):
    z_i = X_test_raw[i]                             # (34,)
    x_hat_i = wls_state_estimation(z_i, H, W)       # (13,)
    z_hat_i = H @ x_hat_i                           # (34,)
    r_i = z_i - z_hat_i                             # (34,)
    R_test_all[i, :] = r_i

    r_i_col = r_i.reshape(-1, 1)
    J_test_all[i] = float(r_i_col.T @ W @ r_i_col)  # J_i = r^T W r

# 将 test 的测量特征与 BDD 统计量拼接，保持与训练时 X_used 的结构一致
J_test_col = J_test_all.reshape(-1, 1)           # (M, 1)
X_test_used = np.hstack([X_test_raw, J_test_col])  # (M, 35)

print("X_test_used shape:", X_test_used.shape)

# -----------------------------
# 5.2 用最佳 XGBoost 模型在全部 normal+FDI 训练数据上重新训练
# -----------------------------
# 注意：这里我们使用和前面 GridSearchCV 找到的最佳参数相同
final_model = XGBClassifier(
    objective="binary:logistic",
    eval_metric="logloss",
    use_label_encoder=False,
    random_state=42,
    n_jobs=-1,
    **grid_xgb.best_params_
)

# 用所有 normal+FDI 样本训练最终模型
final_model.fit(X_used, y_bin)

# -----------------------------
# 5.3 在 test_feature 上预测 0/1 标签
# -----------------------------
y_test_pred = final_model.predict(X_test_used)   # (M,)

# 确保输出是整数 0/1
y_test_pred = y_test_pred.astype(int)

print("Test predictions shape:", y_test_pred.shape)
print("Unique predicted labels:", np.unique(y_test_pred))

# -----------------------------
# 5.4 保存为 <surname>_<cid>.npy
# -----------------------------
out_filename = 'Zhang_06045839.npy'  # TODO: 替换为你的姓和学号，例如 'Zhang_12345678.npy'
np.save(out_filename, y_test_pred)

print("Saved predictions to:", out_filename)

def assess(y_pred):
    assert np.all((y_pred == 0) | (y_pred == 1))
    assert len(y_pred.shape) == 1
    assert y_pred.shape[0] == 1200